services:
  db:
    image: mariadb:latest
    container_name: mariadb_windows
    restart: always
    environment:
      # Configuraci√≥n inicial de la base de datos
      MARIADB_ROOT_PASSWORD: my_password
      MARIADB_DATABASE: smartocupation
      MARIADB_USER: root
      MARIADB_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: